# Generated by Django 4.1.7 on 2023-04-01 03:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_image_alter_comment_stars'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='datetime_created_test',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Date Time of Creation'),
        ),
    ]
