# Generated by Django 4.1.7 on 2023-04-01 03:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_product_datetime_created_test_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='datetime_created_test',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Date Time of Creation'),
        ),
        migrations.AlterField(
            model_name='product',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
