# Generated by Django 4.1.7 on 2023-04-01 04:09

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_datetime_created_test_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='datetime_created_test',
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
